# Generated by Django 5.2.9 on 2025-12-11 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Law",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Nomi")),
                (
                    "name_ru",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Nomi (rus)"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Qisqa nomi"
                    ),
                ),
                (
                    "law_type",
                    models.CharField(
                        choices=[
                            ("code", "Kodeks"),
                            ("law", "Qonun"),
                            ("decree", "Farmon"),
                            ("resolution", "Qaror"),
                            ("regulation", "Nizom"),
                            ("instruction", "Yo'riqnoma"),
                        ],
                        default="law",
                        max_length=20,
                        verbose_name="Turi",
                    ),
                ),
                (
                    "number",
                    models.CharField(blank=True, max_length=50, verbose_name="Raqami"),
                ),
                (
                    "adoption_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Qabul qilingan sana"
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Kuchga kirgan sana"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Amalda"),
                            ("amended", "O'zgartirilgan"),
                            ("repealed", "Bekor qilingan"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                ("source_url", models.URLField(blank=True, verbose_name="Manba URL")),
                (
                    "is_indexed",
                    models.BooleanField(default=False, verbose_name="Indekslangan"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
            ],
            options={
                "verbose_name": "Qonun",
                "verbose_name_plural": "Qonunlar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Nomi")),
                (
                    "contract_type",
                    models.CharField(max_length=50, verbose_name="Shartnoma turi"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                (
                    "template_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="templates/",
                        verbose_name="Shablon fayli",
                    ),
                ),
                (
                    "template_text",
                    models.TextField(blank=True, verbose_name="Shablon matni"),
                ),
                (
                    "required_sections",
                    models.JSONField(default=list, verbose_name="Majburiy bo'limlar"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Tasdiqlangan"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "related_laws",
                    models.ManyToManyField(
                        blank=True,
                        related_name="templates",
                        to="legal_database.law",
                        verbose_name="Tegishli qonunlar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shartnoma shabloni",
                "verbose_name_plural": "Shartnoma shablonlari",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LawChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20, verbose_name="Raqami")),
                ("title", models.CharField(max_length=500, verbose_name="Nomi")),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Nomi (rus)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
                (
                    "law",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="legal_database.law",
                        verbose_name="Qonun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bob",
                "verbose_name_plural": "Boblar",
                "ordering": ["law", "order"],
            },
        ),
        migrations.CreateModel(
            name="LawArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20, verbose_name="Raqami")),
                ("title", models.CharField(max_length=500, verbose_name="Nomi")),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Nomi (rus)"
                    ),
                ),
                ("content", models.TextField(verbose_name="Mazmuni")),
                (
                    "content_ru",
                    models.TextField(blank=True, verbose_name="Mazmuni (rus)"),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=False, verbose_name="Majburiy"),
                ),
                (
                    "applies_to",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Qaysi shartnoma turlariga tegishli",
                        verbose_name="Qo'llaniladi",
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Kalit so'zlar"
                    ),
                ),
                (
                    "embedding",
                    models.BinaryField(blank=True, null=True, verbose_name="Embedding"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "law",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="legal_database.law",
                        verbose_name="Qonun",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="legal_database.lawchapter",
                        verbose_name="Bob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modda",
                "verbose_name_plural": "Moddalar",
                "ordering": ["law", "order"],
            },
        ),
        migrations.CreateModel(
            name="LegalRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("mandatory_clause", "Majburiy band"),
                            ("prohibited_clause", "Taqiqlangan band"),
                            ("recommended_clause", "Tavsiya etilgan band"),
                            ("format_rule", "Format talabi"),
                            ("party_rule", "Tomon talabi"),
                            ("term_rule", "Muddat talabi"),
                            ("payment_rule", "To'lov talabi"),
                        ],
                        max_length=30,
                        verbose_name="Qoida turi",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Jiddiy"),
                            ("high", "Yuqori"),
                            ("medium", "O'rta"),
                            ("low", "Past"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Jiddiylik",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Nomi")),
                ("description", models.TextField(verbose_name="Tavsif")),
                (
                    "condition",
                    models.TextField(
                        help_text="Qoida qachon qo'llaniladi", verbose_name="Shart"
                    ),
                ),
                (
                    "validation_pattern",
                    models.TextField(
                        blank=True,
                        help_text="Regex yoki AI prompt",
                        verbose_name="Tekshirish patterni",
                    ),
                ),
                (
                    "applies_to_contract_types",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Shartnoma turlari"
                    ),
                ),
                (
                    "suggestion_template",
                    models.TextField(blank=True, verbose_name="Tavsiya shabloni"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="legal_database.lawarticle",
                        verbose_name="Modda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Huquqiy qoida",
                "verbose_name_plural": "Huquqiy qoidalar",
                "ordering": ["article", "severity"],
            },
        ),
    ]
