# Generated by Django 5.2.9 on 2025-12-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legal_database", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contracttemplate",
            name="name_cyrillic",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Nomi (kirill)"
            ),
        ),
        migrations.AddField(
            model_name="contracttemplate",
            name="name_ru",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Nomi (rus)"
            ),
        ),
        migrations.AddField(
            model_name="contracttemplate",
            name="template_text_cyrillic",
            field=models.TextField(blank=True, verbose_name="Shablon matni (kirill)"),
        ),
        migrations.AddField(
            model_name="contracttemplate",
            name="template_text_ru",
            field=models.TextField(blank=True, verbose_name="Shablon matni (rus)"),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="name",
            field=models.CharField(max_length=500, verbose_name="Nomi (lotin)"),
        ),
        migrations.AlterField(
            model_name="contracttemplate",
            name="template_text",
            field=models.TextField(blank=True, verbose_name="Shablon matni (lotin)"),
        ),
    ]
