# Generated by Django 5.2.9 on 2025-12-11 13:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("in_progress", "Jarayonda"),
                            ("completed", "Tugallandi"),
                            ("failed", "Xatolik"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "overall_score",
                    models.IntegerField(default=0, verbose_name="Umumiy ball"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Past (70-100)"),
                            ("medium", "O'rta (30-70)"),
                            ("high", "Yuqori (0-30)"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Xavf darajasi",
                    ),
                ),
                (
                    "compliance_score",
                    models.IntegerField(default=0, verbose_name="Qonunga moslik balli"),
                ),
                (
                    "completeness_score",
                    models.IntegerField(default=0, verbose_name="To'liqlik balli"),
                ),
                (
                    "clarity_score",
                    models.IntegerField(default=0, verbose_name="Aniqlik balli"),
                ),
                (
                    "balance_score",
                    models.IntegerField(default=0, verbose_name="Muvozanat balli"),
                ),
                (
                    "summary",
                    models.TextField(blank=True, verbose_name="Qisqacha tahlil"),
                ),
                (
                    "recommendations",
                    models.JSONField(default=list, verbose_name="Tavsiyalar"),
                ),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Qayta ishlash vaqti (soniya)",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Xatolik xabari"),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Ishlatilgan model"
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Model versiyasi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tugallangan"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="contracts.contract",
                        verbose_name="Shartnoma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tahlil natijasi",
                "verbose_name_plural": "Tahlil natijalari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        choices=[
                            ("missing_clause", "Yetishmayotgan band"),
                            ("invalid_clause", "Noto'g'ri band"),
                            ("one_sided", "Bir tomonlama band"),
                            ("unclear", "Noaniq band"),
                            ("conflict", "Ziddiyatli band"),
                            ("illegal", "Noqonuniy band"),
                            ("missing_info", "Yetishmayotgan ma'lumot"),
                            ("format", "Format xatoligi"),
                            ("other", "Boshqa"),
                        ],
                        max_length=30,
                        verbose_name="Muammo turi",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Jiddiy"),
                            ("high", "Yuqori"),
                            ("medium", "O'rta"),
                            ("low", "Past"),
                            ("info", "Ma'lumot"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Jiddiylik",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Sarlavha")),
                ("description", models.TextField(verbose_name="Tavsif")),
                (
                    "section_reference",
                    models.CharField(blank=True, max_length=100, verbose_name="Bo'lim"),
                ),
                (
                    "clause_reference",
                    models.CharField(blank=True, max_length=100, verbose_name="Band"),
                ),
                (
                    "text_excerpt",
                    models.TextField(blank=True, verbose_name="Matn bo'lagi"),
                ),
                (
                    "law_name",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Qonun nomi"
                    ),
                ),
                (
                    "law_article",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Qonun moddasi"
                    ),
                ),
                ("law_text", models.TextField(blank=True, verbose_name="Qonun matni")),
                ("suggestion", models.TextField(blank=True, verbose_name="Tavsiya")),
                (
                    "suggested_text",
                    models.TextField(blank=True, verbose_name="Tavsiya etilgan matn"),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Hal qilingan"),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="Hal qilish izohi"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="analysis.analysisresult",
                        verbose_name="Tahlil",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Hal qilgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Muammo",
                "verbose_name_plural": "Muammolar",
                "ordering": ["severity", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("correct", "To'g'ri"),
                            ("partially_correct", "Qisman to'g'ri"),
                            ("incorrect", "Noto'g'ri"),
                            ("missed", "O'tkazib yuborilgan"),
                        ],
                        max_length=20,
                        verbose_name="Baho turi",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Izoh")),
                (
                    "correct_answer",
                    models.TextField(blank=True, verbose_name="To'g'ri javob"),
                ),
                (
                    "is_used_for_training",
                    models.BooleanField(
                        default=False, verbose_name="O'qitish uchun ishlatilgan"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="analysis.analysisresult",
                        verbose_name="Tahlil",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="analysis.complianceissue",
                        verbose_name="Muammo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teskari aloqa",
                "verbose_name_plural": "Teskari aloqalar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LawReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "law_name",
                    models.CharField(max_length=500, verbose_name="Qonun nomi"),
                ),
                (
                    "article_number",
                    models.CharField(max_length=50, verbose_name="Modda raqami"),
                ),
                (
                    "article_title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Modda nomi"
                    ),
                ),
                ("article_text", models.TextField(verbose_name="Modda matni")),
                (
                    "relevance_reason",
                    models.TextField(blank=True, verbose_name="Tegishlilik sababi"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="law_references",
                        to="analysis.analysisresult",
                        verbose_name="Tahlil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qonun havolasi",
                "verbose_name_plural": "Qonun havolalari",
            },
        ),
    ]
