# Generated by Django 5.0.4 on 2025-12-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_expand_issue_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceissue',
            name='issue_type',
            field=models.CharField(choices=[('missing_clause', 'Yetishmayotgan band'), ('invalid_clause', "Noto'g'ri band"), ('one_sided', 'Bir tomonlama band'), ('unclear', 'Noaniq band'), ('conflict', 'Ziddiyatli band'), ('illegal', 'Noqonuniy band'), ('missing_info', "Yetishmayotgan ma'lumot"), ('format', 'Format xatoligi'), ('spelling', 'Imloviy xato'), ('grammar', 'Grammatik xato'), ('other', 'Boshqa')], max_length=30, verbose_name='Muammo turi'),
        ),
    ]
