# Generated by Django 5.2.9 on 2025-12-11 13:10

import apps.reports.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
        ("contracts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("analysis", "Tahlil hisoboti"),
                            ("compliance", "Qonunga moslik hisoboti"),
                            ("risk", "Xavf hisoboti"),
                            ("summary", "Qisqacha hisobot"),
                            ("full", "To'liq hisobot"),
                        ],
                        default="full",
                        max_length=20,
                        verbose_name="Hisobot turi",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "Word"),
                            ("html", "HTML"),
                            ("json", "JSON"),
                        ],
                        default="pdf",
                        max_length=10,
                        verbose_name="Format",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="Sarlavha")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.reports.models.report_upload_path,
                        verbose_name="Fayl",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, verbose_name="Fayl hajmi"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="analysis.analysisresult",
                        verbose_name="Tahlil",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="contracts.contract",
                        verbose_name="Shartnoma",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hisobot",
                "verbose_name_plural": "Hisobotlar",
                "ordering": ["-created_at"],
            },
        ),
    ]
