# Generated by Django 5.2.9 on 2025-12-15 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="format",
            new_name="report_format",
        ),
    ]
