# Generated by Django 5.2.9 on 2025-12-11 13:10

import apps.contracts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Shartnoma raqami"
                    ),
                ),
                (
                    "original_file",
                    models.FileField(
                        upload_to=apps.contracts.models.contract_upload_path,
                        verbose_name="Asl fayl",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Fayl nomi"),
                ),
                (
                    "file_type",
                    models.CharField(max_length=20, verbose_name="Fayl turi"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Fayl hajmi (bayt)"
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(blank=True, verbose_name="Ajratilgan matn"),
                ),
                (
                    "is_scanned",
                    models.BooleanField(
                        default=False, verbose_name="Skanlangan hujjat"
                    ),
                ),
                (
                    "ocr_confidence",
                    models.FloatField(
                        blank=True, null=True, verbose_name="OCR ishonchliligi"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Shartnoma nomi"
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("service", "Xizmat ko'rsatish shartnomasi"),
                            ("supply", "Mol yetkazib berish shartnomasi"),
                            ("work", "Pudrat shartnomasi"),
                            ("labor", "Mehnat shartnomasi"),
                            ("lease", "Ijara shartnomasi"),
                            ("loan", "Qarz shartnomasi"),
                            ("agency", "Agentlik shartnomasi"),
                            ("commission", "Komissiya shartnomasi"),
                            ("franchise", "Franchayzing shartnomasi"),
                            ("procurement", "Davlat xaridi shartnomasi"),
                            ("other", "Boshqa"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Shartnoma turi",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("uz-latn", "O'zbek (lotin)"),
                            ("uz-cyrl", "Ўзбек (кирилл)"),
                            ("ru", "Русский"),
                            ("mixed", "Aralash"),
                        ],
                        default="uz-latn",
                        max_length=10,
                        verbose_name="Til",
                    ),
                ),
                (
                    "party_a",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="1-tomon"
                    ),
                ),
                (
                    "party_a_inn",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="1-tomon INN"
                    ),
                ),
                (
                    "party_b",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="2-tomon"
                    ),
                ),
                (
                    "party_b_inn",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="2-tomon INN"
                    ),
                ),
                (
                    "contract_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Shartnoma sanasi"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Boshlanish sanasi"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tugash sanasi"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=20,
                        null=True,
                        verbose_name="Umumiy summa",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="UZS", max_length=10, verbose_name="Valyuta"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama"),
                            ("uploaded", "Yuklangan"),
                            ("processing", "Qayta ishlanmoqda"),
                            ("analyzed", "Tahlil qilingan"),
                            ("reviewed", "Ko'rib chiqilgan"),
                            ("approved", "Tasdiqlangan"),
                            ("rejected", "Rad etilgan"),
                            ("archived", "Arxivlangan"),
                        ],
                        default="uploaded",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Izohlar")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tahlil qilingan"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_contracts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tayinlangan",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_contracts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yuklagan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shartnoma",
                "verbose_name_plural": "Shartnomalar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("header", "Sarlavha"),
                            ("parties", "Tomonlar"),
                            ("subject", "Shartnoma predmeti"),
                            ("rights", "Huquqlar"),
                            ("obligations", "Majburiyatlar"),
                            ("price", "Narx va to'lov"),
                            ("delivery", "Yetkazib berish"),
                            ("quality", "Sifat talablari"),
                            ("warranty", "Kafolat"),
                            ("liability", "Javobgarlik"),
                            ("force_majeure", "Fors-major"),
                            ("dispute", "Nizolarni hal qilish"),
                            ("term", "Muddat"),
                            ("termination", "Bekor qilish"),
                            ("confidential", "Maxfiylik"),
                            ("additional", "Qo'shimcha shartlar"),
                            ("requisites", "Rekvizitlar"),
                            ("signatures", "Imzolar"),
                            ("other", "Boshqa"),
                        ],
                        max_length=30,
                        verbose_name="Bo'lim turi",
                    ),
                ),
                (
                    "section_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Bo'lim raqami"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Sarlavha"
                    ),
                ),
                ("content", models.TextField(verbose_name="Mazmun")),
                (
                    "start_position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Boshlanish pozitsiyasi"
                    ),
                ),
                (
                    "end_position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tugash pozitsiyasi"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
                (
                    "is_compliant",
                    models.BooleanField(null=True, verbose_name="Qonunga mos"),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Past"),
                            ("medium", "O'rta"),
                            ("high", "Yuqori"),
                        ],
                        max_length=20,
                        verbose_name="Xavf darajasi",
                    ),
                ),
                (
                    "issues",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Muammolar"
                    ),
                ),
                (
                    "suggestions",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Tavsiyalar"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="contracts.contract",
                        verbose_name="Shartnoma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shartnoma bo'limi",
                "verbose_name_plural": "Shartnoma bo'limlari",
                "ordering": ["contract", "order"],
            },
        ),
        migrations.CreateModel(
            name="ContractComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Izoh")),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Hal qilingan"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Hal qilingan vaqt"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Yangilangan"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="contracts.contract",
                        verbose_name="Shartnoma",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Hal qilgan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="contracts.contractsection",
                        verbose_name="Bo'lim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shartnoma izohi",
                "verbose_name_plural": "Shartnoma izohlari",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractClause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clause_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Band raqami"
                    ),
                ),
                ("content", models.TextField(verbose_name="Mazmun")),
                (
                    "is_standard",
                    models.BooleanField(default=True, verbose_name="Standart band"),
                ),
                (
                    "is_one_sided",
                    models.BooleanField(default=False, verbose_name="Bir tomonlama"),
                ),
                ("is_risky", models.BooleanField(default=False, verbose_name="Xavfli")),
                (
                    "risk_description",
                    models.TextField(blank=True, verbose_name="Xavf tavsifi"),
                ),
                (
                    "related_law",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Tegishli qonun"
                    ),
                ),
                (
                    "law_article",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Qonun moddasi"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Tartib"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clauses",
                        to="contracts.contractsection",
                        verbose_name="Bo'lim",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shartnoma bandi",
                "verbose_name_plural": "Shartnoma bandlari",
                "ordering": ["section", "order"],
            },
        ),
        migrations.CreateModel(
            name="ContractVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="Versiya raqami"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.contracts.models.contract_upload_path,
                        verbose_name="Fayl",
                    ),
                ),
                (
                    "changes_description",
                    models.TextField(blank=True, verbose_name="O'zgarishlar tavsifi"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Yaratilgan"),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="contracts.contract",
                        verbose_name="Shartnoma",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaratgan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shartnoma versiyasi",
                "verbose_name_plural": "Shartnoma versiyalari",
                "ordering": ["contract", "-version_number"],
                "unique_together": {("contract", "version_number")},
            },
        ),
    ]
