# Generated by Django 5.0.4 on 2025-12-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_expand_party_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='party_a',
            field=models.TextField(blank=True, verbose_name='1-tomon'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='party_b',
            field=models.TextField(blank=True, verbose_name='2-tomon'),
        ),
    ]
